Sprint2
oier-elorrieta/R3-ASIER-JONM-JONV pull request #3
Opened 2021-03-03 09:44 UTC by AsierAio

2021-03-03 11:03 UTC, AsierAio commented
ez du balio

2021-03-04 15:58 UTC, oier-elorrieta requested changes
Oso lan txukuna egiten ari zarete. Hala ere hainbat aldaketa/zalantza eskatu dizkizuet. Oso gutxira zaudete bigarren sprintaren oneritzia jasotzeko.

Animo!!!!

2021-03-04 15:58 UTC, oier-elorrieta commented on Conexion/Erronka3/src/main/java/Modelo/ConexionBD.java
> +			System.out.println("Conexion establecida");
Sysoak soberan

2021-03-04 15:58 UTC, oier-elorrieta commented on Conexion/Erronka3/src/main/java/Vista/Hasiera.java
> +		btnaprovisionamiento = new JButton("Aprovisionamientos");
Gazteleraz dauzkazuen botoiak etabar, euskaraz hobeto

2021-03-04 15:58 UTC, oier-elorrieta commented on Conexion/Erronka3/src/main/java/Modelo/Metodoak.java
> +	public static String[] irakurriarray() {
Metodo hau ez dakit zergatik agertzen den....

2021-03-04 15:58 UTC, oier-elorrieta commented on Conexion/Erronka3/src/main/java/Vista/Login.java
> +					System.out.println(num);
Println?

2021-03-04 15:58 UTC, oier-elorrieta commented on Conexion/Erronka3/src/main/java/Vista/PanelResumen.java
> +		setLayout(null);
Zergatik dago sententzia berdina bi aldiz?

2021-03-04 15:58 UTC, oier-elorrieta commented on Erronka3/src/main/java/Modelo/ConexionBD.java
> +			System.out.println("Error al cargar el a");
Syso hauek soberan daude

2021-03-04 15:58 UTC, oier-elorrieta commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +		Produktuak[] arrayobj = new Produktuak[5];
Zenbat produkto egon ahal da ID berdinarekin? Bt baino gehiago ala bat? Array bat beharrezkoa da? Zergatik bost elementuko arraya?

2021-03-04 15:58 UTC, oier-elorrieta commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +				System.out.println(NIF.getNif());
Syso....

2021-03-04 15:58 UTC, oier-elorrieta commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +			System.out.println("ondo");
Syso...

2021-03-04 15:58 UTC, oier-elorrieta commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +				if (resul.next()) {
Dagoeneko hasieratuta dago true balioarekin. If batekin nahikoa izango zen. Ez da behar if-else. Hainbat metodotan daukazue hau.

2021-03-04 15:58 UTC, oier-elorrieta commented on Erronka3/src/main/java/Modelo/Modelo.java
> +	private double[] arrayprezio= new double [10];
Zergatik 10 posizioko arraya. Zer gertatzen da 10 produktu baino gehiago aukeratuz gero?

2021-03-05 09:26 UTC, AsierAio commented on Conexion/Erronka3/src/main/java/Modelo/ConexionBD.java
> +			System.out.println("Conexion establecida");
eginda

2021-03-05 09:30 UTC, AsierAio commented on Conexion/Erronka3/src/main/java/Vista/Login.java
> +					System.out.println(num);
eginda

2021-03-05 09:33 UTC, AsierAio commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +				System.out.println(NIF.getNif());
eginda

2021-03-05 09:33 UTC, AsierAio commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +			System.out.println("ondo");
eginda

2021-03-05 09:35 UTC, AsierAio commented on Erronka3/src/main/java/Modelo/ConexionBD.java
> +			System.out.println("Error al cargar el a");
eginda

2021-03-05 09:42 UTC, AsierAio commented on Conexion/Erronka3/src/main/java/Vista/Hasiera.java
> +		btnaprovisionamiento = new JButton("Aprovisionamientos");
eginda

2021-03-05 11:31 UTC, AsierAio commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +				if (resul.next()) {
eginda

2021-03-05 12:58 UTC, JonV-elorrieta commented on Conexion/Erronka3/src/main/java/Vista/PanelResumen.java
> +		setLayout(null);
eginda

2021-03-05 13:00 UTC, JonV-elorrieta commented on Conexion/Erronka3/src/main/java/Modelo/Metodoak.java
> +	public static String[] irakurriarray() {
eginda

2021-03-08 08:42 UTC, AsierAio commented on Erronka3/src/main/java/Modelo/Modelo.java
> +	private double[] arrayprezio= new double [10];
eginda

2021-03-08 08:42 UTC, AsierAio commented on Erronka3/src/main/java/Modelo/Metodoak.java
> +		Produktuak[] arrayobj = new Produktuak[5];
eginda

2021-03-09 10:43 UTC, oier-elorrieta approved these changes
Ontzat ematen dut

2021-03-09 11:58 UTC, oier-elorrieta approved these changes

2021-03-09 12:08 UTC, merged